### ISSUE TITLE
Parser not working as expected

### ISSUE THREAD

**Issue by christophhart** [BitFunnel/NativeJIT#72]
The example parser seems to produce some unexpected results.

```cpp
Test A:  2 * 2 + 1 = 6 // should be 5
Test B:  1 + 1 + 1 = error // should be 3
Test C:  1 * 2 * 3 = error // should be 6
```

Fixes:

- change `parseSum()` in `parseProduct()` to `parseProduct()` (fixes **A** + **C**)
- change right expression parsing in `parseSum()` to `parseSum` (fixes **B**)

**Comment by MikeHopcroft** [comment]
Thanks for the fix! I added all of the test cases above, and they all pass, but I wasn't able to reproduce the problem with "1 * 2 * 3" before applying the fix. Please feel free to reopen this issue if you find a problem with this case.
