### ISSUE TITLE
Is this project dead?

### ISSUE THREAD

**Issue by ktf** [BitFunnel/NativeJIT#78]
I see there is no commit since 2017. Is this considered a dead project or just a very stable one?

**Comment by MikeHopcroft** [comment]
It's not dead - more stable. We're doing most of our work on the [BitFunne](https://github.com/BitFunnel/BitFunnel) project, which incorporates NativeJIT as a subtree. We did get a [pull request](https://github.com/BitFunnel/NativeJIT/pull/76) back in June, which led to a [more recent pull request](https://github.com/BitFunnel/NativeJIT/pull/77) by BitFunnel team member Jonathan Goodwin. This latter PR is awaiting code review.

Please let us know your interest in this project and whether there are features or capabilities you were hoping for.

**Comment by ktf** [comment]
Thank you for your answer. I will give it  a try and let you know.

**Comment by MikeHopcroft** [comment]
Let us know if you need any help or advice. In my experience, NativeJIT seems pretty stable, but it does have some quirky limitations.
