### ISSUE TITLE
Windows 7 Installation Issues 

### ISSUE THREAD

**Issue by josephjaspers** [BitFunnel/NativeJIT#79]
Commands:
 ./Configure_MSVC 
cmake build-msvc   (from native-jit folder)

Windows7 
Latest version of Cmake
VS2017 (though it detects to use 2015 tools during build). 

neither build directory release or debug contain any type of libs. When running the native.sln I receive numerous 'cmd.exe error 3'

Not sure what caused this, both builds succeeded.
-JJ

**Comment by josephjaspers** [comment]
Closing as it seems to relates to a firewall protection.

**Comment by MikeHopcroft** [comment]
Thanks for the bug report (even though you managed to resolve the issue on your own). Let us know if you have any questions or need help.
